import { Product } from './types';

export const CURRENCY = '£';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'ProMax Ultra Noise-Canceling Headphones',
    slug: 'promax-headphones',
    price: 299.99,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=1',
    description: 'Silence the world and your inner thoughts. Premium build, heavy bass.',
    isDupeCandidate: true,
    rating: 4.8,
    reviews: 124,
    specs: { 'Battery': '30h', 'ANC': 'Active' }
  },
  {
    id: '2',
    title: 'SoundBuddy Lite',
    slug: 'soundbuddy-lite',
    price: 59.99,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=2',
    description: 'Surprisingly adequate sound for the price of a nice dinner.',
    isDupeCandidate: false,
    rating: 4.2,
    reviews: 856,
    specs: { 'Battery': '24h', 'ANC': 'Passive' }
  },
  {
    id: '3',
    title: 'Designer Leather Tote',
    slug: 'designer-tote',
    price: 450.00,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=3',
    description: 'It holds things. But famously.',
    isDupeCandidate: true,
    rating: 4.9,
    reviews: 32,
  },
  {
    id: '4',
    title: 'Vegan Leather Shopper',
    slug: 'vegan-shopper',
    price: 45.00,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=4',
    description: 'Looks 90% the same, costs 10% as much. Do the math.',
    isDupeCandidate: false,
    rating: 4.5,
    reviews: 210,
  },
  {
    id: '5',
    title: 'Smart Espresso Barista Pro',
    slug: 'espresso-pro',
    price: 1200.00,
    category: 'Kitchen',
    image: 'https://picsum.photos/400/400?random=5',
    description: 'For when you need caffeine with a side of engineering degree.',
    isDupeCandidate: true,
    rating: 5.0,
    reviews: 12,
  },
  {
    id: '6',
    title: 'French Press Classic',
    slug: 'french-press',
    price: 25.00,
    category: 'Kitchen',
    image: 'https://picsum.photos/400/400?random=6',
    description: 'Hot water. Beans. Plunge. Don\'t overcomplicate morning survival.',
    isDupeCandidate: false,
    rating: 4.7,
    reviews: 5000,
  },
  {
    id: '7',
    title: '4K Drone Flyer Extreme',
    slug: 'drone-extreme',
    price: 899.00,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=7',
    description: 'Spy on your neighbors in high definition. (Please don\'t actually).',
    isDupeCandidate: true,
    rating: 4.6,
    reviews: 88,
  },
  {
    id: '8',
    title: 'Mini Quadcopter',
    slug: 'mini-quad',
    price: 49.00,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=8',
    description: 'It flies. It crashes. It\'s fun for 10 minutes.',
    isDupeCandidate: false,
    rating: 4.1,
    reviews: 300,
  }
];

export const COPY = {
  cartEmpty: "Your cart is emptier than my soul. Fix that.",
  cartFull: "Blimey, that's a hefty haul—sure you're not opening a shop?",
  checkout: "Take my money!",
  impulseTitle: "Impulse Coach",
  dupeAlert: "Hold your horses, Rockefeller.",
  footer: "© 2024 Shopaholics Inc. We enable you because we care (about revenue).",
};
